apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-private
  namespace: {{ $.Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-dns-private
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: applications/external-dns/{{ $.Values.env }}
    repoURL: https://github.com/gft-blx/k8s-tm-platform
    targetRevision: HEAD
    helm:
      releaseName: external-dns-private
      valueFiles:
        - values-{{ $.Values.env }}-private.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
