apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver
  namespace: {{ $.Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: secrets-store-csi-driver
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: applications/secrets-store-csi-driver/{{ $.Values.env }}
    repoURL: https://github.com/gft-blx/k8s-tm-platform
    targetRevision: HEAD
    helm:
      releaseName: secrets-store-csi-driver
      valueFiles:
        - values-{{ $.Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
