apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-client-secret
spec:
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore
  target:
    name: argocd-repo-creds-github-enterprise-creds
    creationPolicy: Merge
  data:
  - secretKey: githubAppPrivateKey
    remoteRef:
      key: {{ .Values.githubAppPrivateKey }}
      version: "AWSCURRENT"
---
{{- if .Values.enableUI }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oauth-app-client-secret
spec:
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
  - secretKey: dex.github.clientSecret
    remoteRef:
      key: {{ .Values.githubOAuthAppSecretName }}
      version: "AWSCURRENT"
{{- end }}
