secrets-store-csi-driver:
  linux:
    enabled: true
    tolerations:
    - key: "node-group"
      operator: "Equal"
      value: "system"
      effect: "NoExecute"
    priorityClassName: system-node-critical
